services:
  backend:
    build:
      context: ./ecommerce-backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: always
    ports:
      - "5024:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION_STRING}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - SmtpSettings__Password=${SMTP_PASSWORD}
      - CloudinarySettings__ApiSecret=${CLOUDINARY_API_SECRET}

  frontend:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    depends_on:
      - backend
